language: python
python:
  - 2.7
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  # On Ubuntu 12.04 numpy is at 1.6.1, SciPy is at 0.9.0 and Cython is at
  # 0.15.1.
  - sudo apt-get install -y -qq libatlas-dev python-numpy python-scipy python-nose cython
  - sudo apt-get install -y -qq python3-numpy python3-scipy python3-nose cython3
  # Remove the Travis preinstalled NumPy
  - pip -y uninstall numpy
  # The Theano code generator requires the development version of Theano and
  # SymPy (for now).
  - pip install --no-deps git+git://github.com/Theano/Theano.git
  - pip install git+git://github.com/sympy/sympy.git
  # Install coverage with pip because there is no Python 3 version in the
  # precise repos.
  - pip install coverage
  - pip freeze
install:
  - python setup.py install
script: nosetests -v --with-coverage --cover-package=pydy_code_gen
