language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-matplotlib
install:
  - "pip install --use-mirrors sympy coverage"
script: nosetests -v --with-coverage --cover-package=pydy_viz
